name: Release with zip

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install grass
      run: make setup
    - name: Create zip
      run: make zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: theme.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
